Upgrade glibc dependency to 2.60.3
bincrafters/conan-harfbuzz pull request #20
Opened 2019-08-21 07:12 UTC by kpeace

This version of the glibc conan package has selinux and libmount as optional
dependencies. Since there is no conan package for libmount, the only way to build harfbuzz is with:
`-o glibc:with_mount=False`

2019-08-21 12:05 UTC, Croydon requested changes
* there is not yet a stable release of a glib 2.60.3. Please consider contributing to get this going
  * we do have a libmount package https://github.com/bincrafters/conan-libmount

2019-08-21 14:42 UTC, kpeace commented
glib 2.60.3 is failing because of:
`conans.errors.ConanException: Missing prebuilt package for 'libmount/2.33.1@bincrafters/stable'`

libmount doesn't exist (yet) in bintray. That is why I assumed the package doesn't exist.
The only way I managed to build harfbuzz is by changing it to depend on glib 2.60.3 and build glib with:
`-o glibc:with_mount=False`

So it seams as if the main issue is to push libmount binaries into bintray...

2019-09-27 14:11 UTC, ericLemanissier commented
@kpeace this is suprising, there really are libmount/2.33.1 binaries on bintray : https://bintray.com/bincrafters/public-conan/libmount%3Abincrafters/2.33.1%3Astable
To the contrary, there is no glib/2.60.3 https://bintray.com/bincrafters/public-conan/glib%3Abincrafters because this version is only in the `testing` channel https://github.com/bincrafters/conan-glib/branches

2020-06-09 10:22 UTC, ericLemanissier commented
glib was upgraded: https://github.com/bincrafters/conan-harfbuzz/commit/9c1630de897c562a3a02f58e9a494fc14da61bd4 and https://github.com/bincrafters/conan-harfbuzz/commit/75ad2711902a030ea394178a4ec2e00d31feb6fc

2020-06-09 10:22 UTC, closed without merging